In [25]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer

In [26]:
df = pd.read_csv('titanic_data_updated.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,no,second,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,yes,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,no,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,yes,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,no,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [27]:
df.drop(['PassengerId','Name', 'Ticket'],axis=1, inplace=True)
df

    Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         no   third    male  22.0      1      0   7.2500   NaN        S
1        yes   first  female  38.0      1      0  71.2833   C85        C
2        yes   third  female  26.0      0      0   7.9250   NaN        S
3        yes   first  female  35.0      1      0  53.1000  C123        S
4         no   third    male  35.0      0      0   8.0500   NaN        S
..       ...     ...     ...   ...    ...    ...      ...   ...      ...
886       no  second    male  27.0      0      0  13.0000   NaN        S
887      yes   first  female  19.0      0      0  30.0000   B42        S
888       no   third  female   NaN      1      2  23.4500   NaN        S
889      yes   first    male  26.0      0      0  30.0000  C148        C
890       no   third    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [28]:
X = df.drop(['Survived'],axis=1)
X

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0     third    male  22.0      1      0   7.2500   NaN        S
1     first  female  38.0      1      0  71.2833   C85        C
2     third  female  26.0      0      0   7.9250   NaN        S
3     first  female  35.0      1      0  53.1000  C123        S
4     third    male  35.0      0      0   8.0500   NaN        S
..      ...     ...   ...    ...    ...      ...   ...      ...
886  second    male  27.0      0      0  13.0000   NaN        S
887   first  female  19.0      0      0  30.0000   B42        S
888   third  female   NaN      1      2  23.4500   NaN        S
889   first    male  26.0      0      0  30.0000  C148        C
890   third    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 8 columns]

In [29]:
y = df['Survived']
y

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: object

In [30]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [46]:
#Column transformer
imputer_col = ColumnTransformer(
   transformers=[('age',SimpleImputer(missing_values=np.nan,strategy='mean'),['Age']),
                  ('embarked',SimpleImputer(missing_values=np.nan, strategy='most_frequent'),['Embarked']),
                   ('cabin',SimpleImputer(missing_values=np.nan,strategy='constant', fill_value='missing', add_indicator=True),['Cabin'])
             ],
            remainder='passthrough',
            verbose_feature_names_out=False
             )
imputer_col.set_output(transform='pandas')
imputer_col.fit(X_train)
X_train = imputer_col.transform(X_train)
X_test =  imputer_col.transform(X_test)

In [39]:
X_train

,Age,Embarked,Cabin,missingindicator_Cabin,Pclass,Sex,SibSp,Parch,Fare
331,45.500000,S,C124,False,first,male,0,0,28.5000
733,23.000000,S,missing,True,second,male,0,0,13.0000
382,32.000000,S,missing,True,third,male,0,0,7.9250
704,26.000000,S,missing,True,third,male,1,0,7.8542
813,6.000000,S,missing,True,third,female,4,2,31.2750
...,...,...,...,...,...,...,...,...,...
106,21.000000,S,missing,True,third,female,0,0,7.6500
270,29.498846,S,missing,True,first,male,0,0,31.0000
860,41.000000,S,missing,True,third,male,2,0,14.1083
435,14.000000,S,B96 B98,False,first,female,1,2,120.0000
102,21.000000,S,D26,False,first,male,0,1,77.2875

In [47]:
X_train.isnull().sum()

Age                       0
Embarked                  0
Cabin                     0
missingindicator_Cabin    0
Pclass                    0
Sex                       0
SibSp                     0
Parch                     0
Fare                      0
dtype: int64

In [48]:
X_test.isnull().sum()

Age                       0
Embarked                  0
Cabin                     0
missingindicator_Cabin    0
Pclass                    0
Sex                       0
SibSp                     0
Parch                     0
Fare                      0
dtype: int64

In [49]:
X_test

,Age,Embarked,Cabin,missingindicator_Cabin,Pclass,Sex,SibSp,Parch,Fare
331,45.500000,S,C124,False,first,male,0,0,28.5000
733,23.000000,S,missing,True,second,male,0,0,13.0000
382,32.000000,S,missing,True,third,male,0,0,7.9250
704,26.000000,S,missing,True,third,male,1,0,7.8542
813,6.000000,S,missing,True,third,female,4,2,31.2750
...,...,...,...,...,...,...,...,...,...
106,21.000000,S,missing,True,third,female,0,0,7.6500
270,29.498846,S,missing,True,first,male,0,0,31.0000
860,41.000000,S,missing,True,third,male,2,0,14.1083
435,14.000000,S,B96 B98,False,first,female,1,2,120.0000
102,21.000000,S,D26,False,first,male,0,1,77.2875